---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ JOB_NAME }}
  labels:
    pipeline: bwt-filtering
    tier: job
spec:
  parallelism: {{ ACTIVE_NODES_NUMBER }}
  template:
    metadata:
      name: {{ JOB_NAME }}
      labels:
        pipeline: bwt-filtering
        tier: worker
    spec:
    initContainers:
    - name: {{ MASTER_CONTAINER_NAME }}
      image: docker.io/ivasilyev/bwt_filtering_pipeline_master:latest
      imagePullPolicy: Always
      command: [python3, /home/docker/scripts/sampledata2jsons_queue.py, -s, {{ SAMPLEDATA }}, -r, {{ REFDATA }}, -m, {{ OUTPUT_MASK }}, -t, {{ THREADS_NUMBER }}, -o, {{ OUTPUT_DIR }}, -q, {{ QUEUE_NAME }}]
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /data1
          name: data1
        - mountPath: /data2
          name: data2
      containers:
      - name: {{ WORKER_CONTAINER_NAME }}
        image: docker.io/ivasilyev/bwt_filtering_pipeline_worker:latest
        imagePullPolicy: Always
        command: [python3, /home/docker/scripts/queue_handler.py, -q, {{ QUEUE_NAME }}]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: data1
          mountPath: /data1
        - name: data2
          mountPath: /data2
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cpu
                operator: In
                values:
                - xeon-e5-2630-v2
                - xeon-e5-2630-v3
      # Persistent volumes (host side)
      volumes:
      - name: data
        hostPath:
          path: /data
      - name: data1
        hostPath:
          path: /data1
      - name: data2
        hostPath:
          path: /data2
      restartPolicy: Never
