apiVersion: v1
kind: Pod
metadata:
  name: bwt-fp-queue
  labels:
    pipeline: bwt-filtering-pipeline
    tier: queue
spec:
  containers:
    - name: bwt-fp-master
      image: docker.io/ivasilyev/bwt_filtering_pipeline_master:latest
      imagePullPolicy: Always
      # Paste the digested queue creation command line
      command: ["python3", "/home/docker/scripts/sampledata2jsons_queue.py", "-s", "/data/sampledata.txt", "-c", "/data/reference/index/vfdb.refdata", "-m", "test", "-o", "/data/test"]
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /data1
          name: data1
        - mountPath: /data2
          name: data2
  volumes:
    - name: data
      hostPath:
        path: /data
    - name: data1
      hostPath:
        path: /data1
    - name: data2
      hostPath:
        path: /data2
  restartPolicy: Never
