apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis
    tier: data
spec:
  containers:
    - name: master
      image: redis:latest
      imagePullPolicy: Always
      command: ["redis-server"]
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
          protocol: TCP
          name: redis-port
