apiVersion: v1
kind: Pod
metadata:
  name: bwt-fp-master
  labels:
    app: redis
spec:
  containers:
    - name: master
      image: docker.io/ivasilyev/bwt_filtering_pipeline_master:latest
      imagePullPolicy: Always
      command: ["python3", "-i", "sampledata2jsons_queue.py", "-s", "/data/sampledata.txt", "-f", "/data/reference/index/vfdb.refdata", "-c", "/data/reference/index/vfdb.refdata", "-m", "test", "-o", "/data/test"]
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
          name: bwt-ffp-port
      volumeMounts:
        - mountPath: /data
          name: nfs
  volumes:
    - name: nfs
      hostPath:
        path: /data
  restartPolicy: Never
