---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: stateful
spec:
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    tier: stateful
spec:
  containers:
    - name: redis
      image: redis:latest
      imagePullPolicy: Always
      command: ["redis-server"]
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
          protocol: TCP
          name: redis
